######################################################################
##
## Filename: spi_driver_common_test.udo
## Created on: Sat Oct 08 16:18:08 中国标准时间 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
