######################################################################
##
## Filename: adi_spi_driver_7_8bit_test.udo
## Created on: Thu Aug 12 13:11:46 中国标准时间 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
