set_property SRC_FILE_INFO {cfile:c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.3/Microblaze_xz.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc rfile:../../../Microblaze_xz.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc id:1 order:EARLY scoped_inst:U1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.3/Microblaze_xz.srcs/constrs_1/new/top.xdc rfile:../../../Microblaze_xz.srcs/constrs_1/new/top.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV23 [get_ports clk_in1]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT33 [get_ports csb_0]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP31 [get_ports sclk_0]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP32 [get_ports sdio_0]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G23 [get_ports csb_1]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23 [get_ports sclk_1]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F24 [get_ports sdio_1]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports {gpio_tri_o[0]}]
