# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/top_xz/top_xz.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz || ORIG_REF_NAME==top_xz} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_microblaze_0_0/top_xz_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_microblaze_0_0 || ORIG_REF_NAME==top_xz_microblaze_0_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_AXI4_ADI_SPI_15_8BIT_0_0/top_xz_AXI4_ADI_SPI_15_8BIT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_AXI4_ADI_SPI_15_8BIT_0_0 || ORIG_REF_NAME==top_xz_AXI4_ADI_SPI_15_8BIT_0_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_AXI4_ADI_SPI_15_8BIT_0_1/top_xz_AXI4_ADI_SPI_15_8BIT_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_AXI4_ADI_SPI_15_8BIT_0_1 || ORIG_REF_NAME==top_xz_AXI4_ADI_SPI_15_8BIT_0_1} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_mdm_1_0/top_xz_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_mdm_1_0 || ORIG_REF_NAME==top_xz_mdm_1_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_rst_clk_wiz_1_100M_0/top_xz_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==top_xz_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_microblaze_0_axi_periph_0/top_xz_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_microblaze_0_axi_periph_0 || ORIG_REF_NAME==top_xz_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_xbar_0/top_xz_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_xbar_0 || ORIG_REF_NAME==top_xz_xbar_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_dlmb_v10_0/top_xz_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_dlmb_v10_0 || ORIG_REF_NAME==top_xz_dlmb_v10_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_ilmb_v10_0/top_xz_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_ilmb_v10_0 || ORIG_REF_NAME==top_xz_ilmb_v10_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_dlmb_bram_if_cntlr_0/top_xz_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_xz_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_ilmb_bram_if_cntlr_0/top_xz_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_xz_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_lmb_bram_0/top_xz_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_lmb_bram_0 || ORIG_REF_NAME==top_xz_lmb_bram_0} -quiet] -quiet

# IP: bd/top_xz/ip/top_xz_axi_gpio_0_0/top_xz_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xz_axi_gpio_0_0 || ORIG_REF_NAME==top_xz_axi_gpio_0_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_microblaze_0_0/top_xz_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_microblaze_0_0 || ORIG_REF_NAME==top_xz_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_microblaze_0_0/top_xz_microblaze_0_0_ooc_debug.xdc

# XDC: bd/top_xz/ip/top_xz_mdm_1_0/top_xz_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_mdm_1_0 || ORIG_REF_NAME==top_xz_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_mdm_1_0/top_xz_mdm_1_0_ooc_trace.xdc

# XDC: bd/top_xz/ip/top_xz_rst_clk_wiz_1_100M_0/top_xz_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==top_xz_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_rst_clk_wiz_1_100M_0/top_xz_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==top_xz_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_dlmb_v10_0/top_xz_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_dlmb_v10_0 || ORIG_REF_NAME==top_xz_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_ilmb_v10_0/top_xz_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_ilmb_v10_0 || ORIG_REF_NAME==top_xz_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_lmb_bram_0/top_xz_lmb_bram_0_ooc.xdc

# XDC: bd/top_xz/ip/top_xz_axi_gpio_0_0/top_xz_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_axi_gpio_0_0 || ORIG_REF_NAME==top_xz_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/ip/top_xz_axi_gpio_0_0/top_xz_axi_gpio_0_0_ooc.xdc

# XDC: bd/top_xz/ip/top_xz_axi_gpio_0_0/top_xz_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_xz_axi_gpio_0_0 || ORIG_REF_NAME==top_xz_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/top_xz/top_xz_ooc.xdc

# XDC: ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_ooc.xdc
