# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.4/Microblaze_xz/Microblaze_xz.srcs/sources_1/bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1.xci
# IP: The module: 'Microblaze_xz_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.4/Microblaze_xz/Microblaze_xz.srcs/sources_1/bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_xz_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.4/Microblaze_xz/Microblaze_xz.srcs/sources_1/bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_xz_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.4/Microblaze_xz/Microblaze_xz.srcs/sources_1/bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1.xci
# IP: The module: 'Microblaze_xz_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.4/Microblaze_xz/Microblaze_xz.srcs/sources_1/bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_xz_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/86183/Desktop/Microblaze_xzjddy/Microblaze_xz_1.4/Microblaze_xz/Microblaze_xz.srcs/sources_1/bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_xz_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
