# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Top.xdc

# Block Designs: bd/Microblaze_xz/Microblaze_xz.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz || ORIG_REF_NAME==Microblaze_xz} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_microblaze_0_0/Microblaze_xz_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_microblaze_0_0 || ORIG_REF_NAME==Microblaze_xz_microblaze_0_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_AXI4_ADI_SPI_15_8BIT_0_0/Microblaze_xz_AXI4_ADI_SPI_15_8BIT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_AXI4_ADI_SPI_15_8BIT_0_0 || ORIG_REF_NAME==Microblaze_xz_AXI4_ADI_SPI_15_8BIT_0_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_axi_gpio_0_0/Microblaze_xz_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_axi_gpio_0_0 || ORIG_REF_NAME==Microblaze_xz_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_axi_gpio_1_0/Microblaze_xz_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_axi_gpio_1_0 || ORIG_REF_NAME==Microblaze_xz_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_mdm_1_1/Microblaze_xz_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_mdm_1_1 || ORIG_REF_NAME==Microblaze_xz_mdm_1_1} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_rst_Clk_100M_0/Microblaze_xz_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_rst_Clk_100M_0 || ORIG_REF_NAME==Microblaze_xz_rst_Clk_100M_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_microblaze_0_axi_periph_0/Microblaze_xz_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Microblaze_xz_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_xbar_0/Microblaze_xz_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_xbar_0 || ORIG_REF_NAME==Microblaze_xz_xbar_0} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_dlmb_v10_1/Microblaze_xz_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_dlmb_v10_1 || ORIG_REF_NAME==Microblaze_xz_dlmb_v10_1} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_ilmb_v10_1/Microblaze_xz_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_ilmb_v10_1 || ORIG_REF_NAME==Microblaze_xz_ilmb_v10_1} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_dlmb_bram_if_cntlr_1/Microblaze_xz_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Microblaze_xz_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_ilmb_bram_if_cntlr_1/Microblaze_xz_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Microblaze_xz_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_lmb_bram_1/Microblaze_xz_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_lmb_bram_1 || ORIG_REF_NAME==Microblaze_xz_lmb_bram_1} -quiet] -quiet

# IP: bd/Microblaze_xz/ip/Microblaze_xz_AXI4_ADI_SPI_7_8BIT_0_0/Microblaze_xz_AXI4_ADI_SPI_7_8BIT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Microblaze_xz_AXI4_ADI_SPI_7_8BIT_0_0 || ORIG_REF_NAME==Microblaze_xz_AXI4_ADI_SPI_7_8BIT_0_0} -quiet] -quiet

# XDC: bd/Microblaze_xz/Microblaze_xz_ooc.xdc
