SET PATH=D:\Work\Keil\ARM\ARMCC\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Java\jdk1.8.0_221\bin;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files\PuTTY\;C:\Program Files\Calibre2\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\Captain\AppData\Local\Microsoft\WindowsApps;
SET CPU_TYPE=STM32F407VGTx
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=SpaceborneBasebandUnit
SET CPU_CLOCK=0x007A1200
"D:\Work\Keil\ARM\ARMCC\Bin\ArmAsm" --Via "spacebornebasebandunit\startup_stm32f407xx._ia"
"D:\Work\Keil\ARM\ARMCC\Bin\ArmCC" --Via "spacebornebasebandunit\can.__i"
"D:\Work\Keil\ARM\ARMCC\Bin\ArmCC" --Via "spacebornebasebandunit\cs25wq256.__i"
